version: '3'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: router_app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/db
      - SHCEMA=router
      - USERNAME=postgres
      - PASSWORD=123
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
       - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123