spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      schema: ${SCHEMA}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

client:
  producer: ${PRODUCER_URL}