spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/db
    username: postgres
    password: 123
    hikari:
      schema: router
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

client:
  producer: ${PRODUCER_URL:localhost}

flyway:
  locations: classpath:db/migration