CREATE SEQUENCE DOCUMENT_ID_SEQUENCE
    MINVALUE 1
    START WITH 50
    INCREMENT BY 50
    OWNED BY document.id;
CREATE SEQUENCE FILE_ID_SEQUENCE
    MINVALUE 1
    START WITH 50
    INCREMENT BY 50
    OWNED BY file.id;